const eleType = [
  { id: 1, type_description: 'paragraph' },
  { id: 2, type_description: 'title' },
  { id: 3, type_description: 'bold_text' },
  { id: 4, type_description: 'image' },
  { id: 5, type_description: 'video' },
];

const aboutComponents = [
  {
    id: 1,
    ele_type_id: 1,
    ele_description: "We're Peak Design. We create thoughtful and delightful solutions for carrying your stuff. Crowdfunding keeps us independent of outside investment, letting us prioritize world-class design, engineering, and customer satisfaction. This is our 8th Kickstarter and these are our best products yet.",
    project_id: 1,
  },
  {
    id: 2,
    ele_type_id: 2,
    ele_description: 'The Travel Line from Peak Design',
    project_id: 1,
  },
  {
    id: 3,
    ele_type_id: 1,
    ele_description: 'Unmatched versatility access organization and aesthetics, all from a company born during a trip around the world and run by a bunch of fidgety ramblers.',
    project_id: 1,
  },
  {
    id: 4,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about001.png',
    project_id: 1,
  },
  {
    id: 5,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about002.png',
    project_id: 1,
  },
  {
    id: 6,
    ele_type_id: 2,
    ele_description: 'Made for Any Traveler',
    project_id: 1,
  },
  {
    id: 7,
    ele_type_id: 1,
    ele_description: 'At Peak, we design gear that we ourselves want to use. Like our customers, we’re a mishmash of creatives, urbanites, parents, dirtbags...often all of the above. That’s why we created a system of packing tools that let you endlessly customize your setup so can carry what you want where you want, and access it whenever you need it.',
    project_id: 1,
  },
  {
    id: 8,
    ele_type_id: 2,
    ele_description: 'Travel Backpack 45L',
    project_id: 1,
  },
  {
    id: 9,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about003.png',
    project_id: 1,
  },
  {
    id: 10,
    ele_type_id: 2,
    ele_description: 'Packing Tools',
    project_id: 1,
  },
  {
    id: 11,
    ele_type_id: 1,
    ele_description: "As prolific travelers, we designed the Travel Backpack 45L to adapt to the endless variety of trips we take. But we didn't stop there. Our full range of Packing Tools (available in our 'Bundle' Rewards) take organization and efficiency to the next level.=Our Packing Tools are also future-proof: planned future Peak Design Travel Bags will utilizethe Cubes and Pouches we are introducing here.",
    project_id: 1,
  },
  {
    id: 12,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about004.png',
    project_id: 1,
  },
  {
    id: 13,
    ele_type_id: 2,
    ele_description: 'Packing Cubes',
    project_id: 1,
  },
  {
    id: 14,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about005.jpg',
    project_id: 1,
  },
  {
    id: 15,
    ele_type_id: 2,
    ele_description: 'Camera Cubes',
    project_id: 1,
  },
  {
    id: 16,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about006.jpg',
    project_id: 1,
  },
  {
    id: 17,
    ele_type_id: 2,
    ele_description: 'Tech Pouch',
    project_id: 1,
  },
  {
    id: 18,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about007.jpg',
    project_id: 1,
  },
  {
    id: 19,
    ele_type_id: 2,
    ele_description: 'Wash Pouch',
    project_id: 1,
  },
  {
    id: 20,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about008.jpg',
    project_id: 1,
  },
  {
    id: 21,
    ele_type_id: 2,
    ele_description: 'Shoe Pouch',
    project_id: 1,
  },
  {
    id: 22,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about009.jpg',
    project_id: 1,
  },
  {
    id: 23,
    ele_type_id: 2,
    ele_description: 'Rain Fly',
    project_id: 1,
  },
  {
    id: 24,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about010.jpg',
    project_id: 1,
  },
  {
    id: 25,
    ele_type_id: 2,
    ele_description: 'And now for the big question.',
    project_id: 1,
  },
  {
    id: 26,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about011.jpg',
    project_id: 1,
  },
  {
    id: 27,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about012.jpg',
    project_id: 1,
  },
  {
    id: 28,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about013.jpg',
    project_id: 1,
  },
  {
    id: 29,
    ele_type_id: 2,
    ele_description: 'Rewards',
    project_id: 1,
  },
  {
    id: 30,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about014.jpg',
    project_id: 1,
  },
  {
    id: 31,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about015.jpg',
    project_id: 1,
  },
  {
    id: 32,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about016.jpg',
    project_id: 1,
  },
  {
    id: 33,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about017.jpg',
    project_id: 1,
  },
  {
    id: 34,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about018.jpg',
    project_id: 1,
  },
  {
    id: 35,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about019.jpg',
    project_id: 1,
  },
  {
    id: 36,
    ele_type_id: 2,
    ele_description: 'Add-On Menu',
    project_id: 1,
  },
  {
    id: 37,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about020.jpg',
    project_id: 1,
  },
  {
    id: 38,
    ele_type_id: 2,
    ele_description: 'Product Specs',
    project_id: 1,
  },
  {
    id: 39,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about021.jpg',
    project_id: 1,
  },
  {
    id: 40,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about022.jpg',
    project_id: 1,
  },
  {
    id: 41,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about023.jpg',
    project_id: 1,
  },
  {
    id: 42,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about024.jpg',
    project_id: 1,
  },
  {
    id: 43,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about025.jpg',
    project_id: 1,
  },
  {
    id: 44,
    ele_type_id: 2,
    ele_description: 'Thank You',
    project_id: 1,
  },
  {
    id: 45,
    ele_type_id: 1,
    ele_description: 'Crowdfunding allows us to design without compromise and run a company that we are proud to work for. We owe our existence to our max_backers, who help us design the most thoughtful carry solutions on the planet. We imagine a world where for-profit companies treat their employees, partners, customers, and communities as peers, and where quality of output is not hindered by the need to squeeze out maximum profit. Your support helps us to realize that goal. Thank you.',
    project_id: 1,
  },
  {
    id: 46,
    ele_type_id: 4,
    ele_description: 'https://s3-us-west-1.amazonaws.com/fec-ingiter/about026.png',
    project_id: 1,
  },
];

const project = [
  {
    id: 1,
    risk_n_challenges: "This is our 8th Kickstarter project since 2011. Through the years we've gotten pretty darn good at setting accurate expectations and delivering on our promises. But no matter how much we've got our poop in a group (official midwestern terminology) things can still go awry. If they do, we solemnly promise to give you full transparency into the issues and solve them in a way that leaves our max_backers happy and proud to support our company. Supply Chain Risk: Sometimes a machine or tool breaks. Sometimes a factory loses power for a day. Sometimes we get the wrong parts or materials in. These things happen from time to time and can affect how long it takes to build our products. Shipping Risk: Global shipping and warehousing logistics is mind-boggling. Hence we outsource that stuff to experts. But even the experts aren't immune to weather, port congestion, and other uncontrollable factors. Acts of God: We're based in San Francisco. That means we could have an earthquake. Or a tech-bro-gone-mad could steal all the Bird scooters and use them to build a giant fire-breathing Nerf gun wielding Bro-Bot programmed to destroy anything without a popped collar. Whatever happens, we'll get through it together.",
  },
];

const offeredTiers = [
  {
    id: 1,
    base_amount: 235,
    title: 'Travel Backpack 45L',
    description: 'Save $65! ($300 MSRP) Get the Travel Backpack 45L and be prepared for any trip.',
    delivery_date: '20181201',
    ships_to: 'Anywhere in the world',
    max_backers: 438,
    project_id: 1,
  },
  {
    id: 2,
    base_amount: 399,
    title: 'Travel Bundle: Backpack + Packing Tools',
    description: 'Save $146! ($545 MSRP) Get the Travel Backpack 45L plus a complete set of Packing Tools that take organization to the next level.',
    delivery_date: '20181201',
    ships_to: 'Anywhere in the world',
    max_backers: 517,
    project_id: 1,
  },
  {
    id: 3,
    base_amount: 429,
    title: 'Travel Bundle + Camera Cube Small',
    description: 'Save $166! ($595 MSRP) Get the Travel Backpack 45L, a complete set of Packing Tools, and a Small Camera Cube for basic photo storage.',
    delivery_date: '20181201',
    ships_to: 'Anywhere in the world',
    max_backers: 689,
    project_id: 1,
  },
  {
    id: 4,
    base_amount: 445,
    title: 'Travel Bundle + Camera Cube Medium',
    description: 'Save $170! ($615 MSRP) Get the Travel Backpack 45L, a complete set of Packing Tools, and a Medium Camera Cube for more photo storage.',
    delivery_date: '20181201',
    ships_to: 'Anywhere in the world',
    max_backers: 621,
    project_id: 1,
  },
  {
    id: 5,
    base_amount: 459,
    title: 'Travel Bundle + Camera Cube Large',
    description: 'Save $176! ($635 MSRP) Get the Travel Backpack 45L, a complete set of Packing Tools, and a Large Camera Cube for heavy pro photo storage.',
    delivery_date: '20181201',
    ships_to: 'Anywhere in the world',
    max_backers: 266,
    project_id: 1,
  },
];

module.exports = {
  eleType,
  aboutComponents,
  project,
  offeredTiers,
};
